name: Keep Streamlit App Awake and Load Secrets

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  keep-awake:
    runs-on: ubuntu-latest

    steps:
      - name: Send request to keep app awake
        run: |
          curl -s -o /dev/null https://homesafe.streamlit.app/

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libglib2.0-0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}" >> .env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env

      - name: Debug environment variables
        run: |
          cat .env

      - name: Start Streamlit app
        run: |
          streamlit run src/backend/app.py
